INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 400, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cat & Dog Food Drive", "Animals", 500, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Toys for Children", "Children", 125, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Meals on Wheels", "Homeless", 75, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Alzheimers Run", "Seniors", 100, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Counseling Sessions", "Domestic Violence", 65, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wig Making", "Cancer Survivors", 1000, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog Harnesses", "Blind & Deaf", 500, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Musical Instruments", "Developmental Disabilities", 315, "7/1/17", "7/31/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("PTSD Counseling", "Military", 80, "7/1/17", "7/31/17");

INSERT INTO users (name, age) VALUES ("Alexis Dorn", 26);
INSERT INTO users (name, age) VALUES ("Jacob Dorn", 27);
INSERT INTO users (name, age) VALUES ("Claire Dorn", 24);
INSERT INTO users (name, age) VALUES ("Patrick Dorn", 51);
INSERT INTO users (name, age) VALUES ("Abby Dorn", 50);
INSERT INTO users (name, age) VALUES ("Bill Dorn", 85);
INSERT INTO users (name, age) VALUES ("Steve Ulrich", 49);
INSERT INTO users (name, age) VALUES ("Amy Ulrich", 45);
INSERT INTO users (name, age) VALUES ("Chris Johnson", 38);
INSERT INTO users (name, age) VALUES ("Jim Ulrich", 84);
INSERT INTO users (name, age) VALUES ("Alisha Bowman", 27);
INSERT INTO users (name, age) VALUES ("Kayla Payne", 27);
INSERT INTO users (name, age) VALUES ("Jason Banning", 27);
INSERT INTO users (name, age) VALUES ("Morgan Johnson", 26);
INSERT INTO users (name, age) VALUES ("Casey Ulrich", 27);
INSERT INTO users (name, age) VALUES ("Taylor Ulrich", 24);
INSERT INTO users (name, age) VALUES ("Kyle Ulrich", 31);
INSERT INTO users (name, age) VALUES ("Sean Pinnow", 32);
INSERT INTO users (name, age) VALUES ("Brady Ulrich", 19);
INSERT INTO users (name, age) VALUES ("Jaren Ulrich", 22);
